#!/usr/bin/env php
<?php

define('FRB_CLI_PATH', __DIR__);
define('FRB_RUN_PATH', getcwd());

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Fortrabbit CLI (Unofficial)', '0.0.1');

// Environmentless commands
$app->add(new Tlr\Frb\Commands\InitCommand);
$app->add(new Tlr\Frb\Commands\MakeEnvironmentCommand);
$app->add(new Tlr\Frb\Commands\CleanLogsCommand);

// Environment commands
$app->add(new Tlr\Frb\Commands\DeployAssetsCommand);
$app->add(new Tlr\Frb\Commands\DeployCommand);
$app->add(new Tlr\Frb\Commands\DownloadDirectoryCommand);
$app->add(new Tlr\Frb\Commands\DownloadDirectoryCommand);
$app->add(new Tlr\Frb\Commands\RemoteRunCommand);
$app->add(new Tlr\Frb\Commands\ResetRemoteCommand);
$app->add(new Tlr\Frb\Commands\SshCommand);
$app->add(new Tlr\Frb\Commands\TouchDeployCommand);

$app->run();
